import { usePage } from '@inertiajs/vue3';
import {
    IconBooks,
    IconBox,
    IconCategory,
    IconChartArrowsVertical,
    IconChartBarPopular,
    IconChartInfographic,
    IconCirclePlus,
    IconClockHour6,
    IconCreditCard,
    IconFileCertificate,
    IconFileDescription,
    IconFolder,
    IconLayout2,
    IconSchool,
    IconShoppingCart,
    IconTable,
    IconUserBolt,
    IconUserShield,
    IconUserSquare,
    IconUsers,
    IconUsersPlus,
    IconTruckDelivery,
    IconReceipt2,
    IconReceipt,
    IconBuildingWarehouse,
    IconArrowsExchange,
    IconClipboardCheck,
    IconArrowBackUp,
    IconArrowForwardUp,
    IconPackage,
    IconId,
    IconAddressBook,
    IconTools,
    IconBuildingBank,
    IconTruck,
    IconMapPin,
    IconAlertTriangle,
    IconFlame,
    IconTrendingDown,
    IconChartArrows,
    IconCalculator,
    IconSettings,
    IconCash,
    IconWallet,
    IconFileInvoice,
    IconBuildingStore,
    IconReceiptTax,
    IconRuler2,
    IconAdjustments,
} from '@tabler/icons-vue';
import hasAnyPermission from './Permission';

export default function useMenu() {
    // define use page
    const { url } = usePage();

    // define menu navigations
    const menuNavigation = [
        {
            title: 'Overview',
            details: [
                {
                    title: 'Dashboard',
                    href: route('dashboard'),
                    active: url === '/dashboard' ? true : false,
                    icon: IconLayout2,
                    permissions: hasAnyPermission(['dashboard-access']),
                },
            ],
        },
        {
            title: 'Data Management',
            details: [
                {
                    title: 'Produk',
                    icon: IconBox,
                    permissions: hasAnyPermission(['products-access']),
                    subdetails: [
                        {
                            title: 'Kategori',
                            href: route('categories.index'),
                            icon: IconFolder,
                            active: url === '/dashboard/categories' ? true : false,
                            permissions: hasAnyPermission(['categories-access']),
                        },
                        {
                            title: 'Data Produk',
                            href: route('products.index'),
                            icon: IconTable,
                            active: url === '/dashboard/products' ? true : false,
                            permissions: hasAnyPermission(['products-access']),
                        },
                        {
                            title: 'Bundling Produk',
                            href: route('product-bundles.index'),
                            icon: IconPackage,
                            active: url.startsWith('/dashboard/product-bundles'),
                            permissions: hasAnyPermission(['products-access']),
                        },
                        {
                            title: 'Master Satuan',
                            href: route('units.index'),
                            icon: IconRuler2,
                            active: url.startsWith('/dashboard/units'),
                            permissions: hasAnyPermission(['products-access']),
                        },
                    ],
                },
                {
                    title: 'Pelanggan',
                    icon: IconUsersPlus,
                    permissions: hasAnyPermission(['customers-access']),
                    subdetails: [
                        {
                            title: 'Data Pelanggan',
                            href: route('customers.index'),
                            icon: IconUsers,
                            active: url === '/dashboard/customers' ? true : false,
                            permissions: hasAnyPermission(['customers-access']),
                        },
                        {
                            title: 'Member',
                            href: route('customers.index', { member: 1 }),
                            icon: IconId,
                            active: url.includes('member=1'),
                            permissions: hasAnyPermission(['customers-access']),
                        },
                        {
                            title: 'Daftar Alamat',
                            href: route('customer-addresses.index'),
                            icon: IconAddressBook,
                            active: url.startsWith('/dashboard/customer-addresses'),
                            permissions: hasAnyPermission(['customers-access']),
                        },
                    ],
                },
                {
                    title: 'Supplier',
                    href: route('suppliers.index'),
                    active: url === '/dashboard/suppliers' ? true : false,
                    icon: IconTruckDelivery,
                    permissions: hasAnyPermission(['products-access']), // Reusing active permission
                },
                {
                    title: 'Master Gudang',
                    href: route('warehouses.index'),
                    active: url === '/dashboard/warehouses',
                    icon: IconBuildingWarehouse,
                    permissions: hasAnyPermission(['products-access']),
                },
                {
                    title: 'Utilities',
                    icon: IconTools,
                    permissions: hasAnyPermission(['products-access']),
                    subdetails: [
                        {
                            title: 'Daftar Rekening Bank',
                            href: route('bank-accounts.index'),
                            icon: IconBuildingBank,
                            active: url.startsWith('/dashboard/bank-accounts'),
                            permissions: hasAnyPermission(['products-access']),
                        },
                        {
                            title: 'Master Alamat',
                            href: route('master-addresses.index'),
                            icon: IconMapPin,
                            active: url.startsWith('/dashboard/master-addresses'),
                            permissions: hasAnyPermission(['products-access']),
                        },
                        {
                            title: 'Jasa Kirim',
                            href: route('shipping-methods.index'),
                            icon: IconTruck,
                            active: url.startsWith('/dashboard/shipping-methods'),
                            permissions: hasAnyPermission(['products-access']),
                        },
                        {
                            title: 'Payment Gateway',
                            href: route('settings.payments.edit'),
                            icon: IconCreditCard,
                            active: url === '/dashboard/settings/payments',
                            permissions: hasAnyPermission(['payment-settings-access']),
                        },
                    ],
                },
            ],
        },
        {
            title: 'Akuntansi',
            details: [
                {
                    title: 'Chart of Accounts',
                    href: route('accounts.index'),
                    active: url.startsWith('/dashboard/accounts') && !url.includes('account-settings'),
                    icon: IconCalculator,
                    permissions: hasAnyPermission(['products-access']),
                },
                {
                    title: 'Setting Akun',
                    href: route('account-settings.index'),
                    active: url.startsWith('/dashboard/account-settings'),
                    icon: IconSettings,
                    permissions: hasAnyPermission(['products-access']),
                },
                {
                    title: 'Aset Tetap',
                    href: route('fixed-assets.index'),
                    active: url.startsWith('/dashboard/fixed-assets'),
                    icon: IconBuildingStore,
                    permissions: hasAnyPermission(['products-access']),
                },
                {
                    title: 'Pajak',
                    icon: IconReceiptTax,
                    permissions: hasAnyPermission(['products-access']),
                    subdetails: [
                        {
                            title: 'Pengaturan Pajak',
                            href: route('tax-settings.index'),
                            active: url.startsWith('/dashboard/tax-settings'),
                            icon: IconReceiptTax,
                            permissions: hasAnyPermission(['products-access']),
                        },
                        {
                            title: 'Master Pajak',
                            href: route('taxes.index'),
                            active: url.startsWith('/dashboard/taxes'),
                            icon: IconReceiptTax,
                            permissions: hasAnyPermission(['products-access']),
                        },
                    ],
                },
                {
                    title: 'Jurnal',
                    href: route('journals.index'),
                    active: url.startsWith('/dashboard/journals'),
                    icon: IconBooks,
                    permissions: hasAnyPermission(['products-access']),
                },
                {
                    title: 'Lap. Laba Rugi',
                    href: route('reports.profit-loss'),
                    active: url.startsWith('/dashboard/reports/profit-loss'),
                    icon: IconChartArrows,
                    permissions: hasAnyPermission(['reports-access']),
                },
                {
                    title: 'Buku Besar',
                    href: route('reports.general-ledger'),
                    active: url.startsWith('/dashboard/reports/general-ledger'),
                    icon: IconBooks,
                    permissions: hasAnyPermission(['reports-access']),
                },
                {
                    title: 'Neraca',
                    href: route('reports.balance-sheet'),
                    active: url.startsWith('/dashboard/reports/balance-sheet'),
                    icon: IconChartInfographic,
                    permissions: hasAnyPermission(['reports-access']),
                },
                {
                    title: 'Arus Kas',
                    href: route('reports.cash-flow'),
                    active: url.startsWith('/dashboard/reports/cash-flow'),
                    icon: IconCash,
                    permissions: hasAnyPermission(['reports-access']),
                },
                {
                    title: 'Laporan Pajak',
                    href: route('reports.tax'),
                    active: url.startsWith('/dashboard/reports/tax'),
                    icon: IconReceiptTax,
                    permissions: hasAnyPermission(['reports-access']),
                },
                {
                    title: 'Kas Masuk/Keluar',
                    href: route('cash-transactions.index'),
                    active: url.startsWith('/dashboard/cash-transactions'),
                    icon: IconArrowsExchange,
                    permissions: hasAnyPermission(['products-access']),
                },
                {
                    title: 'Kas Kecil',
                    href: route('petty-cash.index'),
                    active: url.startsWith('/dashboard/petty-cash'),
                    icon: IconWallet,
                    permissions: hasAnyPermission(['products-access']),
                },
                {
                    title: 'Piutang',
                    icon: IconFileInvoice,
                    permissions: hasAnyPermission(['products-access']),
                    subdetails: [
                        {
                            title: 'Daftar Piutang',
                            href: route('receivables.index'),
                            active: url.startsWith('/dashboard/receivables') && !url.includes('payment-history'),
                            icon: IconFileInvoice,
                            permissions: hasAnyPermission(['products-access']),
                        },
                        {
                            title: 'Riwayat Pembayaran Piutang',
                            href: route('receivables.payment-history'),
                            active: url.startsWith('/dashboard/receivables/payment-history'),
                            icon: IconFileInvoice,
                            permissions: hasAnyPermission(['products-access']),
                        },
                    ],
                },
                {
                    title: 'Hutang',
                    icon: IconCreditCard,
                    permissions: hasAnyPermission(['products-access']),
                    subdetails: [
                        {
                            title: 'Daftar Hutang',
                            href: route('payables.index'),
                            active: url.startsWith('/dashboard/payables') && !url.includes('payment-history'),
                            icon: IconCreditCard,
                            permissions: hasAnyPermission(['products-access']),
                        },
                        {
                            title: 'Riwayat Pembayaran Hutang',
                            href: route('payables.payment-history'),
                            active: url.startsWith('/dashboard/payables/payment-history'),
                            icon: IconCreditCard,
                            permissions: hasAnyPermission(['products-access']),
                        },
                    ],
                },
            ],
        },
        {
            title: 'Inventory',
            details: [
                {
                    title: 'Stok In/Out',
                    href: route('stock-adjustments.index'),
                    active: url.startsWith('/dashboard/stock-adjustments'),
                    icon: IconArrowsExchange,
                    permissions: hasAnyPermission(['products-access']),
                },
                {
                    title: 'Stock Opname',
                    href: route('stock-opnames.index'),
                    active: url.startsWith('/dashboard/stock-opnames'),
                    icon: IconClipboardCheck,
                    permissions: hasAnyPermission(['products-access']),
                },
                {
                    title: 'Stock Penyesuaian',
                    href: route('stock-penyesuaian.index'),
                    active: url.startsWith('/dashboard/stock-penyesuaian'),
                    icon: IconAdjustments,
                    permissions: hasAnyPermission(['products-access']),
                },
                {
                    title: 'Zero-Value Trans.',
                    href: route('zero-value-transactions.index'),
                    active: url.startsWith('/dashboard/zero-value-transactions'),
                    icon: IconAlertTriangle,
                    permissions: hasAnyPermission(['products-access']),
                },
                {
                    title: 'Stok Gudang',
                    icon: IconBuildingWarehouse,
                    permissions: hasAnyPermission(['reports-access']),
                    subdetails: [
                        {
                            title: 'Stok per Gudang',
                            href: route('reports.warehouse-stock'),
                            active: url.startsWith('/dashboard/reports/warehouse-stock') && !url.includes('bundle'),
                            icon: IconTable,
                            permissions: hasAnyPermission(['reports-access']),
                        },
                        {
                            title: 'Stok Bundling',
                            href: route('reports.bundle-warehouse-stock'),
                            active: url.startsWith('/dashboard/reports/bundle-warehouse-stock'),
                            icon: IconPackage,
                            permissions: hasAnyPermission(['reports-access']),
                        },
                    ],
                },
                {
                    title: 'Stok Minimal',
                    href: route('reports.minimum-stock'),
                    active: url.startsWith('/dashboard/reports/minimum-stock'),
                    icon: IconAlertTriangle,
                    permissions: hasAnyPermission(['reports-access']),
                },
                {
                    title: 'Perputaran Stock',
                    icon: IconChartArrows,
                    permissions: hasAnyPermission(['reports-access']),
                    subdetails: [
                        {
                            title: 'Fast Moving',
                            href: route('reports.fast-moving'),
                            active: url.startsWith('/dashboard/reports/fast-moving'),
                            icon: IconFlame,
                            permissions: hasAnyPermission(['reports-access']),
                        },
                        {
                            title: 'Slow Moving',
                            href: route('reports.slow-moving'),
                            active: url.startsWith('/dashboard/reports/slow-moving'),
                            icon: IconTrendingDown,
                            permissions: hasAnyPermission(['reports-access']),
                        },
                    ],
                },
            ],
        },
        {
            title: 'Pembelian',
            details: [
                {
                    title: 'Pembelian',
                    href: route('purchases.index'),
                    active: url.startsWith('/dashboard/purchases'),
                    icon: IconReceipt2,
                    permissions: hasAnyPermission(['products-access']),
                },
                {
                    title: 'Return Pembelian',
                    href: route('purchase-returns.index'),
                    active: url.startsWith('/dashboard/purchase-returns'),
                    icon: IconArrowBackUp,
                    permissions: hasAnyPermission(['products-access']),
                },
            ],
        },
        {
            title: 'Penjualan',
            details: [
                {
                    title: 'POS-Kasir',
                    href: route('transactions.index'),
                    active: url === '/dashboard/transactions' ? true : false,
                    icon: IconShoppingCart,
                    permissions: hasAnyPermission(['transactions-access']),
                },
                {
                    title: 'Transaksi',
                    href: route('sales.index'),
                    active: url.startsWith('/dashboard/sales'),
                    icon: IconReceipt,
                    permissions: hasAnyPermission(['transactions-access']),
                },
                {
                    title: 'Verifikasi Finance',
                    icon: IconFileCertificate,
                    permissions: hasAnyPermission(['sales-approve-finance']),
                    subdetails: [
                        {
                            title: 'Pending Approval',
                            href: route('approvals.finance.index'),
                            active: url === '/dashboard/approvals/finance',
                            icon: IconClockHour6,
                            permissions: hasAnyPermission(['sales-approve-finance']),
                        },
                        {
                            title: 'History Approval',
                            href: route('approvals.finance.history'),
                            active: url === '/dashboard/approvals/finance/history',
                            icon: IconBooks,
                            permissions: hasAnyPermission(['sales-approve-finance']),
                        },
                    ],
                },
                {
                    title: 'Verifikasi Gudang',
                    icon: IconClipboardCheck,
                    permissions: hasAnyPermission(['sales-approve-warehouse']),
                    subdetails: [
                        {
                            title: 'Pending Approval',
                            href: route('approvals.warehouse.index'),
                            active: url === '/dashboard/approvals/warehouse',
                            icon: IconClockHour6,
                            permissions: hasAnyPermission(['sales-approve-warehouse']),
                        },
                        {
                            title: 'History Approval',
                            href: route('approvals.warehouse.history'),
                            active: url === '/dashboard/approvals/warehouse/history',
                            icon: IconBooks,
                            permissions: hasAnyPermission(['sales-approve-warehouse']),
                        },
                    ],
                },
                {
                    title: 'Return Penjualan',
                    href: route('sale-returns.index'),
                    active: url.startsWith('/dashboard/sale-returns'),
                    icon: IconArrowForwardUp,
                    permissions: hasAnyPermission(['transactions-access']),
                },
                {
                    title: 'Riwayat POS',
                    href: route('transactions.history'),
                    active: url === '/dashboard/transactions/history' ? true : false,
                    icon: IconClockHour6,
                    permissions: hasAnyPermission(['transactions-access']),
                },
                {
                    title: 'Old Order',
                    icon: IconReceiptTax,
                    permissions: hasAnyPermission(['transactions-access']),
                    subdetails: [
                        {
                            title: 'Old Order',
                            href: route('old-orders.index'),
                            active: url.startsWith('/dashboard/old-orders') && !url.includes('resume'),
                            icon: IconReceipt2,
                            permissions: hasAnyPermission(['transactions-access']),
                        },
                        {
                            title: 'Resume old order',
                            href: route('old-orders.resume'),
                            active: url.startsWith('/dashboard/old-orders/resume') && !url.includes('report'),
                            icon: IconClockHour6,
                            permissions: hasAnyPermission(['transactions-access']),
                        },
                        // {
                        //     title: 'Produk Resume',
                        //     href: route('old-orders.product-resume'),
                        //     active: url.startsWith('/dashboard/old-orders/product-resume'),
                        //     icon: IconBooks,
                        //     permissions: hasAnyPermission(['transactions-access']),
                        // },
                        {
                            title: 'Laporan Resume',
                            href: route('old-orders.resume-report'),
                            active: url.startsWith('/dashboard/old-orders/resume-report'),
                            icon: IconChartBarPopular,
                            permissions: hasAnyPermission(['transactions-access']),
                        },
                    ],
                },
            ],
        },
        {
            title: 'Laporan',
            details: [
                {
                    title: 'Laporan Penjualan',
                    href: route('reports.sales.index'),
                    active: url.startsWith('/dashboard/reports/sales'),
                    icon: IconChartArrowsVertical,
                    permissions: hasAnyPermission(['reports-access']),
                },
                {
                    title: 'Laporan Keuntungan',
                    href: route('reports.profits.index'),
                    active: url.startsWith('/dashboard/reports/profits'),
                    icon: IconChartBarPopular,
                    permissions: hasAnyPermission(['profits-access']),
                },
                {
                    title: 'Laporan Stok',
                    href: route('reports.stocks.index'),
                    active: url.startsWith('/dashboard/reports/stocks'),
                    icon: IconChartInfographic,
                    permissions: hasAnyPermission(['reports-access']),
                },
                {
                    title: 'Laporan Stok In/Out',
                    href: route('reports.stock-adjustments.index'),
                    active: url.startsWith('/dashboard/reports/stock-adjustments'),
                    icon: IconArrowsExchange,
                    permissions: hasAnyPermission(['reports-access']),
                },
                {
                    title: 'Laporan HPP',
                    href: route('reports.cogs'),
                    active: url.startsWith('/dashboard/reports/cogs'),
                    icon: IconCalculator,
                    permissions: hasAnyPermission(['reports-access']),
                },
            ],
        },
        {
            title: 'User Management',
            details: [
                {
                    title: 'Akses',
                    icon: IconUserBolt,
                    permissions: hasAnyPermission(['permissions-access', 'roles-access']),
                    subdetails: [
                        {
                            title: 'Hak Akses',
                            href: route('permissions.index'),
                            icon: IconUserBolt,
                            active: url === '/dashboard/permissions',
                            permissions: hasAnyPermission(['permissions-access']),
                        },
                        {
                            title: 'Akses Group',
                            href: route('roles.index'),
                            icon: IconUserShield,
                            active: url === '/dashboard/roles',
                            permissions: hasAnyPermission(['roles-access']),
                        },
                    ],
                },
                {
                    title: 'Pengguna',
                    icon: IconUsers,
                    permissions: hasAnyPermission(['users-access']),
                    subdetails: [
                        {
                            title: 'Data Pengguna',
                            href: route('users.index'),
                            icon: IconTable,
                            active: url === '/dashboard/users' ? true : false,
                            permissions: hasAnyPermission(['users-access']),
                        },
                        {
                            title: 'Tambah Data Pengguna',
                            href: route('users.create'),
                            icon: IconCirclePlus,
                            active:
                                url === '/dashboard/users/create'
                                    ? true
                                    : false,
                            permissions: hasAnyPermission(['users-create']),
                        },
                    ],
                },
            ],
        },
    ];

    return menuNavigation;
}

